site_name: fastapi-skeleton
site_url: https://github.com/oryon-dominik/skeleton-fastapi/docs
repo_url: https://github.com/oryon-dominik/skeleton-fastapi

edit_uri: ''
dev_addr: 127.0.0.1:8000

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep orange

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange

nav:
  - Home: index.md
  - About: about.md

plugins:
  - render_swagger

extra_css:
  - css/openapi-darkmode-fix.css
